import { createSupabaseClient } from "@/utils/supabase/server";
import { checkEntitlement } from "@/utils/supabase/entitlements";
import ReportsDashboard from "@/components/reports-dashboard";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";

export default async function ReportsPage() {
  const { data: entitlementData, error: entitlementError } = await checkEntitlement("premium");

  if (entitlementError) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Card className="p-6">
          <h2 className="text-xl font-semibold text-red-600">Error</h2>
          <p className="mt-2 text-muted-foreground">
            There was an error checking your access permissions.
          </p>
        </Card>
      </div>
    );
  }

  const client = await createSupabaseClient();
  const { data: { user } } = await client.auth.getUser();

  if (!user) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Card className="p-6">
          <h2 className="text-xl font-semibold">Authentication Required</h2>
          <p className="mt-2 text-muted-foreground">
            Please sign in to access reports.
          </p>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold">Multi-Year Equity Intelligence</h1>
        <p className="text-muted-foreground mt-2">
          10-K analysis powered by multi-agent AI
        </p>
      </div>

      {/* Research & AI Disclaimer */}
      <Card className="p-6 border-slate-200 bg-slate-50">
        <div>
          <h3 className="font-semibold text-slate-800 mb-3">⚠️ Important Disclaimers</h3>
          <div className="space-y-3 text-sm text-slate-700">
            <p>
              <strong>Research Purposes Only:</strong> These reports are provided for informational and research purposes only. They do not constitute investment advice, recommendations, or solicitations to buy or sell securities. Always consult with qualified financial professionals before making investment decisions.
            </p>
            <p>
              <strong>AI-Generated Content:</strong> These analyses are generated by artificial intelligence systems and may contain errors, omissions, or inaccuracies. The AI may misinterpret data, make incorrect calculations, or draw flawed conclusions. Users should independently verify all information and exercise critical judgment when reviewing AI-generated content.
            </p>
          </div>
        </div>
      </Card>

      <ReportsDashboard 
        userId={user.id} 
        hasFullAccess={entitlementData?.hasAccess || false} 
      />
    </div>
  );
}
